# Generated by Django 2.2.6 on 2019-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_link', models.CharField(max_length=255)),
                ('img_local_link', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('cat', models.ManyToManyField(to='fashion_catalogue.Category')),
            ],
        ),
    ]
