# Generated by Django 2.2.6 on 2019-10-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='size',
        ),
    ]
