# Generated by Django 2.2.6 on 2019-10-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0002_auto_20191012_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionitem',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='fashionitem',
            name='img_local_link',
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
