# Generated by Django 2.2.6 on 2019-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0003_auto_20191012_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
