# Generated by Django 2.2.6 on 2019-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0004_auto_20191012_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='item_source',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='parsing_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='img',
            field=models.ImageField(null=True, upload_to='static/images/product'),
        ),
    ]
