# Generated by Django 2.2.6 on 2019-10-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0005_auto_20191013_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='fashionitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='fashionitem',
            name='size',
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='color',
            field=models.ManyToManyField(to='fashion_catalogue.Color'),
        ),
        migrations.AddField(
            model_name='fashionitem',
            name='size',
            field=models.ManyToManyField(to='fashion_catalogue.Size'),
        ),
    ]
