# Generated by Django 2.2.6 on 2019-10-14 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0006_auto_20191013_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
