# Generated by Django 2.2.6 on 2019-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0009_auto_20191014_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
