# Generated by Django 2.2.6 on 2019-10-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0010_auto_20191014_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='cat',
            field=models.ManyToManyField(null=True, to='fashion_catalogue.Category'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='color',
            field=models.ManyToManyField(null=True, to='fashion_catalogue.Color'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='size',
            field=models.ManyToManyField(null=True, to='fashion_catalogue.Size'),
        ),
    ]
