# Generated by Django 2.2.6 on 2019-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0011_auto_20191014_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='cat',
            field=models.ManyToManyField(to='fashion_catalogue.Category'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='color',
            field=models.ManyToManyField(to='fashion_catalogue.Color'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='item_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='parsing_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='size',
            field=models.ManyToManyField(to='fashion_catalogue.Size'),
        ),
        migrations.AlterField(
            model_name='fashionitem',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
