# Generated by Django 2.2.6 on 2019-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0013_auto_20191018_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionitem',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
