# Generated by Django 2.2.6 on 2019-10-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0014_auto_20191018_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('moderated', models.BooleanField(default=False)),
                ('fashion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion_catalogue.FashionItem')),
            ],
        ),
    ]
