# Generated by Django 2.2.6 on 2019-10-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_catalogue', '0016_auto_20191020_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
